### PR TITLE
Try/Catch Return Label fixes

### LINKED ISSUE #192: Support for GotoExpression values
`TryEmitGoto` is marked with a TODO for supporting `GotoExpression` values - I'd like to have a try at implementing this, at least for some scenarios.

`Expression.Return()` creates a `GotoExpression` of `GotoExpressionKind.Return`, which needs to know if it's being emitted within a `Try` expression, as `OpCodes.Leave` must then be used instead of `OpCodes.Ret`. `Leave` needs access to the `returnLabel` and `returnResult` defined in `TryEmitTryCatchFinallyBlock`.

I'm therefore thinking I should:

1. Add `ParentFlags.Try` to indicate if code is being emitted within a Try
2. Add a `TryCatchFinallyInfo` class - similar to `BlockInfo` - to own `returnLabel` and `returnResult`
3. Add `PushTry()` and `PopTry()` methods to `ClosureInfo`, used similarly to `PushBlock()` and `PopBlock()`
4. Update `TryEmitGoto()` to emit `GotoExpression` values and support `GotoExpressionKind.Return`, using `OpCodes.Ret` or `OpCodes.Leave` as appropriate

Before I get started, please could you let me know if this sounds like an acceptable / sensible approach?

Cheers,

Steve

### PR DESCRIPTION
**Pull request by SteveWilkes**
- Using a once-created stack of `BlockInfo`s in `ClosureInfo` instead of creating `BlockInfo`s as part of `TryCollectBoundConstants` and then again in `TryEmit` - also removes need for `BlockInfo.Parent` and `BlockInfo.Empty`

- Using a stack of `TryCatchFinallyInfo`s in `ClosureInfo` to keep track of `ReturnExpression` use; fixes #192

### CODE REVIEW

**Comment by dadhi** [comment]
Amazing! Thank you. Will review it shortly.

**Comment by dadhi** [comment]
Here may be a problem with collecting blocks together with constants, because there is API `TryCompileLambdaWithPredefinedClosure` and the `TryCompile..` without closure (forgot the name). These specifically cutting off collecting the constants imroving the perf. where its known. Example is ObjectMethodExecutor from IssueTests.

So, you should rely on collecting constants for emitter.

**Comment by SteveWilkes** [comment]
Hmm, ok - so to support `TryCompileWithPreCreatedClosure` and `TryCompileWithoutClosure`, I could add tests including blocks to `PreConstructedClosureTests`, and make them pass?

**Comment by dadhi** [comment]
> I could add tests including blocks to PreConstructedClosureTests, and make them pass?

Yep.

**Comment by dadhi** [comment]
@SteveWilkes,

I was thinking about the GoTo's in general and it seems that there is no way to implement them optimally without the first cycling though the expression and marking all blocks and labels. This is because of arbitrary jump - so it may not be possible to do in one swoop.

Assuminng this is indeed a true, there couple of alternatives.

1. Do not support labels / gotos in specialized methods which provide or do not provide the external closure object.  Simply, if `TryCatch...Info`s are not available in ClosureInfo then fallback (`return false`).
2. Other... mmm.. mat be sinplified visitor to just collect the block / label info.

What do you think?

**Comment by SteveWilkes** [comment]
Yep! We've now got test coverage and support for blocks, blocks with variables and try/catches in Expressions compiled using `TryCompileWithPreCreatedClosure` and `TryCompileWithoutClosure`.

Ultimately, you now support more scenarios than you did before, so I think continuing without those methods supporting Gotos is acceptable. `TryEmitGoto` currently throws an `InvalidOperationException` if it can't find a Label - that could be changed to throw a `NotSupportedException` or return false if it's a pre-created closure?

`TryCompileWithPreCreatedClosure` accepting `ConstantExpression`s kind of sets a precedent for the user populating parts of the `ClosureInfo`, so you could have an overload with a configuration Action passed in to add Labels? Like:

```C#
lambda.TryCompileWithPreCreatedClosure<Func<X>>(
    closure,
    closureConfig =>
    {
        closureConfig.AddLabels(labelTarget1, labelTarget2);
        closureConfig.MarkLabelAsTryReturn(labelTarget2);
    });
```

`ClosureInfo` could then implement a public `IClosureConfig` interface, and be passed as the `closureConfig` into the Action?

**Comment by dadhi** [comment]
@SteveWilkes Thank you, great work.

> `ClosureInfo` could then implement a public `IClosureConfig` interface, and be passed as the closureConfig into the Action?

I am fine if you prototype something like this... Or we can wait if someone will request it (including us).

File: src/FastExpressionCompiler/FastExpressionCompiler.cs [hunk 1]
```diff
@@ -226,11 +226,13 @@ public static Delegate CompileFast(this LambdaExpression lambdaExpr, bool ifFast
             return (TDelegate)(object)method.CreateDelegate(delegateType, closure);
         }
 
+        private static readonly object _staticDelegateClosurePlaceholder = new object();
```
Comment (dadhi) [inline src/FastExpressionCompiler/FastExpressionCompiler.cs]: Nice null-object here :)

**Comment by SteveWilkes** [comment]
> @SteveWilkes Thank you, great work.
> 
> > `ClosureInfo` could then implement a public `IClosureConfig` interface, and be passed as the closureConfig into the Action?
> 
> I am fine if you prototype something like this... Or we can wait if someone will request it (including us).

You're welcome!

I suspect a large majority of FEC's use will be with auto-created closures, so let's see if someone requests it :)
