### PR TITLE
Fix type of TypeAs expression to match framework

### LINKED ISSUE #185: InvalidCastException for TypeAs
Trying to replace some of my expressions with LightExpression (version 2.0.0) and the following causes an exception `Unable to cast object of type 'FastExpressionCompiler.LightExpression.TypeBinaryExpression' to type 'FastExpressionCompiler.LightExpression.UnaryExpression'.`

```C#
ParameterExpression parameter = Expression.Parameter(typeof(object));
            Func<object, string> tryCast =
                Expression.Lambda<Func<object, string>>(
                    Expression.TypeAs(parameter, typeof(string)),
                    parameter
                ).CompileFast();
```
Happy to take a stab at a PR if you like?

### PR DESCRIPTION
**Pull request by samcragg**
Fixes #185

### CODE REVIEW

File: src/FastExpressionCompiler.LightExpression/Expression.cs [hunk 1]
```diff
@@ -180,8 +180,8 @@ public static MemberExpression MakeMemberAccess(Expression expression, MemberInf
         public static UnaryExpression Not(Expression operand) =>
             new UnaryExpression(ExpressionType.Not, operand, operand.Type);
 
-        public static TypeBinaryExpression TypeAs(Expression operand, Type type) =>
-            new TypeBinaryExpression(ExpressionType.TypeAs, operand, type);
```
Comment (dadhi) [inline src/FastExpressionCompiler.LightExpression/Expression.cs]: Looks good, but does `TypeBinaryExpression` is used anywhere now. If not, we can remove it.

Comment (samcragg) [reply src/FastExpressionCompiler.LightExpression/Expression.cs]: It's used for `TypeIs` and for `TypeEqual`
I've fixed the same error with TypeIs and added support for TypeEqual - happy to move the latter into a separate PR.

If you like, I'd be happy to create another PR that adds unit tests for the different XxxExpression classes to make sure that the API matches the framework one?

Comment (dadhi) [reply src/FastExpressionCompiler.LightExpression/Expression.cs]: I will merge this PR and you can tackle the other cases separately - good idea.
