### PR TITLE
Fix #310 - nullable conversion with ignored result

### LINKED ISSUE #310: InvalidProgramException when nullable result is ignored
The error occurs when I have a Convert expression returning Nullable<int>, but I ignore the result. For example

```csharp
[Test]
public void Case2_A()
{
  var p = Parameter(typeof(int), "tmp0");
  var expr = 
    Lambda<Action<int>>(Block(
      Convert(p, typeof(int?)),
      Default(typeof(void))), p);

  var f = expr.CompileFast();
  f(2);
}
```

Or similar:

```csharp

[Test]
public void Case2_B()
{
  var p = Parameter(typeof(int), "tmp0");
  var expr = 
    Lambda<Action<int>>(Convert(p, typeof(int?)), new[] { p });
  var f = expr.CompileFast();
  f(2);
}
```

In these simple cases, I could just not place the ignored convert there, but it also fails in more complex cases when the conversion is nested in conditions/blocks, but the result is still not used in the end.

### PR DESCRIPTION
**Pull request by exyi**
It should also help a bit other conversions with ignored result -
whenever we know what the conversion will always pass, we
don't need to emit any code. In some cases, this may save a boxing
conversion (and it will probably save some work for the JIT)

### CODE REVIEW

File: test/FastExpressionCompiler.TestsRunner/Program.cs [hunk 1]
```diff
@@ -226,6 +226,9 @@ void Run(Func<int> run, string name = null)
                 Run(new Issue308_Wrong_delegate_type_returned_with_closure().Run);
                 Run(new FastExpressionCompiler.LightExpression.IssueTests.Issue308_Wrong_delegate_type_returned_with_closure().Run);
 
+                Run(new Issue310_InvalidProgramException_ignored_nullable().Run);
+                Run(new FastExpressionCompiler.LightExpression.IssueTests.Issue310_InvalidProgramException_ignored_nullable().Run);
+
```
Comment (dadhi) [inline test/FastExpressionCompiler.TestsRunner/Program.cs:231]: The same test run should be added to net472 test runner, another Program.cs
Otherwise, great PR. Thank you. Waiting for this change and merging.

**Review by dadhi — CHANGES_REQUESTED** [review]

File: test/FastExpressionCompiler.TestsRunner/Program.cs (hunk 1 above)
Comment (exyi) [reply test/FastExpressionCompiler.TestsRunner/Program.cs:231]: Ok good point, should be fixed now

**Comment by dadhi** [comment]
Great, merging.
